### ISSUE TITLE
install.sh pip: command not found

### ISSUE THREAD

**Issue by joechu1** [jefflester/minitrino#13]
There's a somewhat confusing message displayed when running the install.sh script:

```./install.sh: line 5: pip: command not found```

This doesn't look like an error, but more of a side effect of testing for the required Python version. However, I think users may get confused whether or not the installation succeeded if they see this message.

You should be able to modify the code to suppress this message without losing any functionality:
```
    if pip --version 2>&1 | grep -q "python3.[6-9]"; then
        PIP=pip
    elif pip3 --version 2>&1 | grep -q "python3.[6-9]"; then
        PIP=pip3
```

Otherwise if you'd rather have a pull request, let me know!

**Comment by jefflester** [comment]
Thank you for pointing this out, @joechu1! I've submitted PR #14 to handle this. In the future, please feel 100% free to create a branch and submit a PR for bug fixes or additional features if you're up for it, and I'm happy to review.
