### ISSUE TITLE
cannot run ./install.sh with a python version higher than 9

### ISSUE THREAD

**Issue by epiekarski** [jefflester/minitrino#43]
In setting up minitrino for the first time, new users are unable to run the ./install.sh script if they are on python version 3.10, which is the latest python version available

**Comment by maura16** [comment]
@jefflester Gonna grab this issue! FYI -- I cannot assign to myself :(

**Comment by jefflester** [comment]
@maura16 I took care of it, the issue is now assigned to you! Let me see if I can elevate your repo permissions so that you can change these things moving forward.
