### ISSUE TITLE
Update SQLServer module connection-url

### ISSUE THREAD

**Issue by epiekarski** [jefflester/minitrino#46]
New updates to the SQL Server connector I believe require ';encrypt=false' to be appended to the end of the connection URL. New URL should be:

connection-url=jdbc:sqlserver://sqlserver:1433;database=master;encrypt=false

Docs for reference:
https://docs.starburst.io/latest/connector/starburst-sqlserver.html#configuration

**Comment by jefflester** [comment]
Closed with #56
